### ISSUE TITLE
Node-Problem-Detector should Patch NodeStatus not Update 

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/node-problem-detector#9] opened 2016-05-26 01:45 UTC
*Problem:*
`kubelet`, `node-controller`, and now the `node-problem-detector` all update the `Node.Status` field.

Normally this is not a problem because if changes happen rapidly, resource version mismatch fails and everything is ok.

When a new field is added to Node Status, however:
* Since `kubelet` and `node-controller` are in the same repository they are recompiled with the new field and Status updates continue to operate normally.
* However, since `node-problem-detector` is in a separate repository and has not been recompiled with the new version, its `Update` calls end up squashing the new (unknown) field, resetting it to `nil`.

*Suggested Solution:*
`node-problem-detector` should do a patch instead of an update to prevent wiping out fields it is not aware of. Incidentally, `kubelet` and `node-controller` should do this as well, but that is not as critical since they are in the same repository and new types are normally added their first.

CC @kubernetes/sig-node @kubernetes/sig-api-machinery @Random-Liu @bgrant0607

**Comment by caesarxuchao** [comment] 2016-05-26 03:49
You can use the [Patch()](https://github.com/kubernetes/kubernetes/blob/master/pkg/client/typed/dynamic/client.go#L185) method in the dynamic client, but you'll need to modify that function to allow specifying a subresource. cc @krousey

**Comment by lavalamp** [comment] 2016-05-26 04:27
I didn't know you guys were building this in a different repository. If you aren't going to be version-locked like the other components are, then you need some features that aren't built into our client.

Patch and/or dynamic client seems to be your best way forward.

There are various ways we could have made this easier, but they won't happen in time for your first release...

**Comment by Random-Liu** [comment] 2016-05-26 05:47
@saad-ali Thanks a lot for reporting!

> You can use the Patch() method in the dynamic client, but you'll need to modify that function to allow specifying a subresource. cc @krousey

I'll try this!

@lavalamp Thanks a lot! Patch is good enough for now~ Let me try :)

**Comment by derekwaynecarr** [comment] 2016-05-26 13:06
I think we should also have a node e2e that verifies the Kubelet itself
does not regress and drop node conditions it does not manage.  I don't
think we have anything that verifies that today and it would help avoid
regressions.

**Comment by dchen1107** [comment] 2016-05-26 14:25
Yes, I talked @Random-Liu on e2e test verifying this.

**Comment by bgrant0607** [comment] 2016-05-26 14:27
@saad-ali Ah, so it was getting clobbered. Great catch!  Where multiple components update a resource, they'll need a way to patch, either via PATCH or via a dedicated subresource. 

This is a problem already with node controller and Kubelet. I'm surprised we hadn't been bit by it yet.

We have a similar problem with kubectl round-tripping, which we're working to eliminate.

**Comment by lavalamp** [comment] 2016-05-26 17:22
@bgrant0607 Yeah. Very surprising this is the first time we've hit this. BTW making kubectl not round-trip wouldn't be sufficient, but @krousey was actually switching everything to use the dynamic client, which *will* be sufficient to prevent this.

Also, this is the canary in the coal mine: everyone who built automation using our current client will have this problem in 1.3.

**Comment by Random-Liu** [comment] 2016-05-26 17:33
> I think we should also have a node e2e that verifies the Kubelet itself
does not regress and drop node conditions it does not manage.  I don't
think we have anything that verifies that today and it would help avoid
regressions.

Yeah, we are going to add test for this. :)

**Comment by Random-Liu** [comment] 2016-05-26 18:10
FYI, I tried many ways to patch the `NodeCondition`, but the apiserver keeps throwing out 405 error. I'll work with @caesarxuchao to figure out how to patch status correctly (Thanks! :)).

And I had an offline discussion with @saad-ali, to unblock him we'll:
* disable node-problem-detector temporarily
* get https://github.com/kubernetes/kubernetes/pull/26351 merged
* update the api client version in node-problem-detector
* re-enable node-problem-detector

Because node-problem-detector only touches `NodeStatus` and #26351 seems to be the only PR for now adding new field in `NodeStatus`, so this could be a temporarily walk around.

At the mean time, I'll change the node-problem-detector to use Patch asap.

@dchen1107 @bgrant0607 @lavalamp Is this OK?

**Comment by Random-Liu** [comment] 2016-05-26 21:01
Offline discussed with @dchen1107, we will:
* Go with https://github.com/kubernetes/node-problem-detector/issues/9#issuecomment-221949895 to unblock @saad-ali
* Wait for https://github.com/kubernetes/kubernetes/pull/26381 to land (Thanks @caesarxuchao )
* Switch node-problem-detector to use `Patch` instead of `UpdateStatus`

**Closed** 2016-06-01 23:26 UTC
Labels: bug

**Comment by wojtek-t** [comment] 2016-06-02 06:27
>
but @krousey was actually switching everything to use the dynamic client, which will be sufficient to prevent this.

@lavalamp - what do you mean by everything? If you really mean "everything", then we need to support protobufs in it, which we currently don't. @smarterclayton FYI

**Comment by lavalamp** [comment] 2016-06-02 20:59
Yeah, dynamic client only talk json right now afaik.
