### ISSUE TITLE
node-problem-detector cannot run in non-privileged mode

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/node-problem-detector#698] opened 2022-09-01 06:49 UTC
/kind bug

### What happened?

Running containers in privileged mode is not recommended as privileged containers run with all [linux capabilities](https://man7.org/linux/man-pages/man7/capabilities.7.html) enabled and can access the host's resources. Running containers in privileged mode opens number of security threads such as breakout to underlying host OS.

Currently the node-problem-detector DaemonSet runs in privileged mode.

https://github.com/kubernetes/node-problem-detector/blob/d8b2940b3cac1d99c9072dd644c7dfb372672114/deployment/node-problem-detector.yaml#L41-L42

Trying to run node-problem-detector in non-privileged mode (even with all capabilities added) one of its monitors fails with:
```
E0808 06:25:33.740326       1 problem_detector.go:55] Failed to start problem daemon &{/config/kernel-monitor.json 0xc00035b7a0 0xc000443100 {{kmsg map[] /dev/kmsg 5m } 10 kernel-monitor [{KernelDeadlock  {0 0 <nil>} KernelHasNoDeadlock kernel has no deadlock} {ReadonlyFilesystem  {0 0 <nil>} FilesystemIsNotReadOnly Filesystem is not read-only}] [{temporary  OOMKilling Killed process \d+ (.+) total-vm:\d+kB, anon-rss:\d+kB, file-rss:\d+kB.*} {temporary  TaskHung task [\S ]+:\w+ blocked for more than \w+ seconds\.} {temporary  UnregisterNetDevice unregister_netdevice: waiting for \w+ to become free. Usage count = \d+} {temporary  KernelOops BUG: unable to handle kernel NULL pointer dereference at .*} {temporary  KernelOops divide error: 0000 \[#\d+\] SMP} {temporary  Ext4Error EXT4-fs error .*} {temporary  Ext4Warning EXT4-fs warning .*} {temporary  IOError Buffer I/O error .*} {temporary  MemoryReadError CE memory read error .*} {permanent KernelDeadlock DockerHung task docker:\w+ blocked for more than \w+ seconds\.} {permanent ReadonlyFilesystem FilesystemIsReadOnly Remounting filesystem read-only}] 0xc00043d21e} [] <nil> 0xc00045aea0 0xc00044bb80}: failed to create kmsg parser: open /dev/kmsg: operation not permitted
``` 

I don't fully understand what it requires to read kernel logs from `/dev/kmsg`.

### What did you expect to happen?

I would expect to be able to run node-problem-detector in non-privileged mode.

**Comment by balu-ce** [comment] 2023-05-04 11:20
Any update on this ?

**Comment by btiernay** [comment] 2023-05-24 02:34
Duplicate of https://github.com/kubernetes/node-problem-detector/issues/625

**Comment by AlexzSouz** [comment] 2023-12-08 11:15
> Duplicate of #625

Both issues DO NOT have a solution for the problem @ialidzhikov mentioned and that I'm currently experiencing. The "duplicate" issue you (@btiernay) shared only contains comments from @k8s-triage-robot. No solution is provided 🤷

Any solution so far?

**Comment by alazyer** [comment] 2023-12-29 07:14
How about trying with plugin of `journald` instead? it works fine for me to detect "NodeOOM", "PodOOM" with pattern ".*Out of memory.*" and ".*Memory cgroup out of memory.*"

**Comment by haardm** [comment] 2024-06-08 00:25
Hello, I am also facing similar issue while reading from /dev/kmsg using NPD while my container is not given privileged mode. Is there any workaround? We only need to read, no mutating actions on our side.

**Closed** 2024-11-05 02:32 UTC
Labels: lifecycle/rotten, needs-kind
