### ISSUE TITLE
Failed to start log monitor "/config/docker-monitor.json": failed to create journal client from path "/var/log/journal": unable to open a handle to the library

### ISSUE THREAD

**Issue by trandainhan** [kubernetes/node-problem-detector#277] opened 2019-05-16 07:47 UTC
after install NDP, i found this log:
`1 problem_detector.go:64] Failed to start log monitor "/config/docker-monitor.json": failed to create journal client from path "/var/log/journal": unable to open a handle to the library`

what does this mean: `unable to open a handle to the library` ?
also, i checked folder `/var/log/journal` in the node, this folder is actually exist. I'm not sure whether NDP docker-monitor actually work or not with this message.

**Comment by jekohk** [comment] 2019-05-16 16:57
I actually ran into the same issue yesterday- what version of `node-problem-detector` are you running? Thisis probably be caused by https://github.com/kubernetes/node-problem-detector/issues/232 in which case you should upgrade to `0.6.2` or `0.6.3`

**Comment by wangzhen127** [comment] 2019-05-31 17:41
Closing this now. Reopen if you still see the problem in 0.6.3.

**Closed by wangzhen127** 2019-05-31 17:41 UTC
